# Generated by Django 5.1.2 on 2024-10-21 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.RemoveField(
            model_name='weekday',
            name='date',
        ),
        migrations.RemoveField(
            model_name='weekday',
            name='task',
        ),
        migrations.AddField(
            model_name='daterange',
            name='week_day',
            field=models.ManyToManyField(related_name='dateranges', to='rasp_app.weekday'),
        ),
        migrations.AlterField(
            model_name='daterange',
            name='left_date',
            field=models.DateField(db_index=True, verbose_name='%d/%m/%Y'),
        ),
        migrations.AlterField(
            model_name='daterange',
            name='right_date',
            field=models.DateField(db_index=True, verbose_name='%d/%m/%Y'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('date_range', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rasp_app.daterange')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rasp_app.lesson')),
                ('week_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rasp_app.weekday')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['week_day'],
            },
        ),
    ]
