# Generated by Django 5.1.2 on 2024-10-17 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp_app', '0004_lesson_remove_weekday_task_alter_daterange_week_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_range',
        ),
        migrations.AlterField(
            model_name='task',
            name='week_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twday', to='rasp_app.weekday'),
        ),
        migrations.AddField(
            model_name='task',
            name='date_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drange', to='rasp_app.daterange'),
        ),
    ]
