# Generated by Django 5.1.2 on 2024-10-17 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp_app', '0006_alter_task_date_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daterange',
            name='week_day',
            field=models.ManyToManyField(related_name='dateranges', to='rasp_app.weekday'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_range',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rasp_app.daterange'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rasp_app.lesson'),
        ),
        migrations.AlterField(
            model_name='task',
            name='week_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rasp_app.weekday'),
        ),
    ]
