# Generated by Django 5.1.2 on 2024-10-17 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp_app', '0007_alter_daterange_week_day_alter_task_date_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rasp_app.daterange'),
        ),
    ]
