# Generated by Django 5.1.2 on 2024-10-18 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp_app', '0008_alter_task_date_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_range',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rasp_app.daterange'),
        ),
    ]
