# Generated by Django 5.1.2 on 2024-10-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasp_app', '0009_alter_task_date_range'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['week_day'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
    ]
