# Generated by Django 5.1.2 on 2024-10-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp_app', '0011_alter_task_date_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(blank=True),
        ),
    ]
