# Generated by Django 5.1.2 on 2024-10-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp_app', '0012_alter_task_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daterange',
            name='left_date',
            field=models.DateField(db_index=True, verbose_name='%d/%m/%Y'),
        ),
        migrations.AlterField(
            model_name='daterange',
            name='right_date',
            field=models.DateField(db_index=True, verbose_name='%d/%m/%Y'),
        ),
    ]
