# Generated by Django 5.1.2 on 2024-10-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp_app', '0013_alter_daterange_left_date_alter_daterange_right_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
